2015/12/29 12:05:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'phone'' in C:\xampp\htdocs\vbapp1.com\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\vbapp1.com\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\vbapp1.com\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\vbapp1.com\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\vbapp1.com\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\vbapp1.com\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\vbapp1.com\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\vbapp1.com\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\vbapp1.com\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\vbapp1.com\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\vbapp1.com\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\vbapp1.com\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\vbapp1.com\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\vbapp1.com\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\vbapp1.com\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\vbapp1.com\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\vbapp1.com\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/vbapp1.com/index.php/gii/model/index
HTTP_REFERER=http://localhost/vbapp1.com/index.php/gii/default/index
---
